package com.example.demo.enums;

public enum ChatbotActionType {
    NONE,
    NAV_LOGIN,
    NAV_RECUPERAR_CONTRASENA,
    NAV_SUBIR_OBRA,
    NAV_SUBIR_SERVICIO,
    NAV_PORTAFOLIO,
    NAV_EXPLORAR,
    NAV_CARRITO,
    NAV_TRANSACCIONES,
    NAV_MENSAJES,
    NAV_SOLICITUDES,
    NAV_NOTIFICACIONES,
    NAV_CONVOCATORIAS,
    NAV_PERFIL,
    NAV_MODERACION,
    NAV_GESTION_USUARIOS
}
