
ALTER TABLE obra
    MODIFY COLUMN imagen1 VARCHAR(1000) NOT NULL,
    MODIFY COLUMN imagen2 VARCHAR(1000) NULL,
    MODIFY COLUMN imagen3 VARCHAR(1000) NULL;

ALTER TABLE usuario
    MODIFY COLUMN foto_perfil VARCHAR(1000) NULL;